name: 'baubyte-website'
services:
  # Servicio de la Aplicación PHP
  baubyte-website:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        UID: 1001
        GID: 1001
    container_name: baubyte-website
    restart: unless-stopped
    volumes:
     # Mapea el directorio 'writable' desde el host al contenedor
      - ./writable:/var/www/html/writable
      # Mapea el archivo '.env' desde el host al contenedor (solo lectura)
      - ./.env:/var/www/html/.env
    networks:
      - baubyte-website-net
      - traefik-proxy # Red compartida con Traefik

  # Servicio del Servidor Web Nginx
  baubyte-website-nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    container_name: baubyte-website-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - baubyte-website
    networks:
      - baubyte-website-net
      - traefik-proxy # Red compartida con Traefik
    labels:
      # --- Etiquetas para Traefik ---
      - "traefik.enable=true" # Habilitar Traefik para este servicio
      - "traefik.http.routers.baubyte.rule=Host(`baubyte.com.ar`, `www.baubyte.com.ar`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure" # Escuchar en el punto de entrada HTTPS
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt" # Usar Let's Encrypt para el certificado
      - "traefik.http.services.portfolio.loadbalancer.server.port=80" # El puerto interno del servicio (nginx escucha en el 80)
      - "traefik.docker.network=traefik-proxy"

networks:
  baubyte-website-net:
    driver: bridge
  traefik-proxy:
    external: true # Usar la red externa creada para Traefik
volumes:
  writable:
    driver: local
  env:
    driver: local