name: 'baubyte-website'
services:
  baubyte-website:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1001
        GID: 1001
    container_name: baubyte-website
    restart: unless-stopped
    environment:
      SSL_MODE: "mixed"  # Escucha tanto HTTP (80) como HTTPS (443)
      LOG_OUTPUT_LEVEL: "warn"
      PHP_OPCACHE_ENABLE: "1"
      PHP_OPCACHE_REVALIDATE_FREQ: "0"
      NGINX_WEBROOT: "/var/www/html/public"
    volumes:
      - ./writable:/var/www/html/writable:rw  # Logs, cache, sesiones, uploads
      - ./.env:/var/www/html/.env:ro          # Configuración del entorno
      - ./public:/var/www/html/public:rw      # Archivos públicos
    networks:
      - baubyte-website-net
      - traefik-proxy # Red compartida con Traefik
    labels:
      # --- Etiquetas para Traefik ---
      - "traefik.enable=true"
      - "traefik.http.routers.baubyte.rule=Host(`baubyte.com.ar`) || Host(`www.baubyte.com.ar`)"
      - "traefik.http.routers.baubyte.entrypoints=websecure"
      - "traefik.http.routers.baubyte.tls.certresolver=letsencrypt" 
      - "traefik.http.services.baubyte.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-proxy"

networks:
  baubyte-website-net:
    driver: bridge
  traefik-proxy:
    external: true #
volumes:
  writable:
    driver: local
  public:
    driver: local