name: 'baubyte-website'
services:
  # Servicio de la Aplicación PHP
  baubyte-website:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: baubyte-website
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - baubyte-website-net
      - traefik-proxy # Red compartida con Traefik

  # Servicio del Servidor Web Nginx
  baubyte-website-nginx:
    image: nginx:1.25-alpine
    container_name: baubyte-website-nginx
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - baubyte-website
    networks:
      - baubyte-website-net
      - traefik-proxy # Red compartida con Traefik
    labels:
      # --- Etiquetas para Traefik ---
      - "traefik.enable=true" # Habilitar Traefik para este servicio
      - "traefik.http.routers.portfolio.rule=Host(`baubyte.com.ar`)" # La URL que escuchará
      - "traefik.http.routers.portfolio.entrypoints=websecure" # Escuchar en el punto de entrada HTTPS
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt" # Usar Let's Encrypt para el certificado
      - "traefik.http.services.portfolio.loadbalancer.server.port=80" # El puerto interno del servicio (nginx escucha en el 80)

networks:
  baubyte-website-net:
    driver: bridge
  traefik-proxy:
    external: true # Usar la red externa creada para Traefik