<?php

namespace App\Support\Icons;

/**
 * Read-only lookup over the vendored `resources/icons/devicon.json` catalog
 * (regenerated by `npm run icons:build` from `@iconify-json/devicon` — see
 * `scripts/build-icon-catalog.mjs`). Server-side only: this file is never
 * shipped to the browser bundle.
 *
 * Icon ids are stored/passed around as `"{prefix}:{name}"` (e.g.
 * `"devicon:laravel"`), matching the `Skill.icon` column format.
 *
 * The decoded catalog is memoized in a static property for the lifetime of
 * the request/process — `search()`/`has()`/`resolve()` are typically called
 * several times per Filament request (options loading, label lookup,
 * validation) and this avoids re-reading/re-decoding the ~5MB JSON file
 * more than once per request.
 */
class IconCatalog
{
    /**
     * @var array{prefix: string, width: int, height: int, icons: array<string, array{body: string, width?: int, height?: int}>, aliases: array<string, array{parent: string}>}|null
     */
    private static ?array $data = null;

    /**
     * Searches icon ids/labels by substring (case-insensitive), returning at
     * most `$limit` matches.
     *
     * @return list<array{id: string, label: string}>
     */
    public static function search(string $term, int $limit = 50): array
    {
        $data = self::data();
        $needle = mb_strtolower(trim($term));
        $results = [];

        foreach (array_keys($data['icons']) as $name) {
            if ($needle !== '' && ! str_contains(mb_strtolower($name), $needle)) {
                continue;
            }

            $results[] = [
                'id' => "{$data['prefix']}:{$name}",
                'label' => self::label($name),
            ];

            if (count($results) >= $limit) {
                break;
            }
        }

        return $results;
    }

    /**
     * Whether `$id` (in `"{prefix}:{name}"` form) exists in the catalog,
     * either as a real icon or as an alias of one.
     */
    public static function has(?string $id): bool
    {
        return self::resolveName($id) !== null;
    }

    /**
     * Resolves `$id` to its raw Iconify icon data (`body`, `width`,
     * `height`), following alias chains. Returns `null` for `null`, an
     * unknown id, or an id under a different icon set prefix.
     *
     * @return array{body: string, width: int, height: int}|null
     */
    public static function resolve(?string $id): ?array
    {
        $data = self::data();
        $name = self::resolveName($id);

        if ($name === null) {
            return null;
        }

        $icon = $data['icons'][$name];

        return [
            'body' => $icon['body'],
            'width' => $icon['width'] ?? $data['width'],
            'height' => $icon['height'] ?? $data['height'],
        ];
    }

    /**
     * The human-readable label for `$id` (e.g. `"devicon:laravel"` ->
     * `"Laravel"`), or `null` when `$id` is null/malformed/unknown.
     */
    public static function labelFor(?string $id): ?string
    {
        $name = self::resolveName($id);

        return $name === null ? null : self::label($name);
    }

    /**
     * Resolves `$id` down to a real (non-alias) icon name, or `null` when
     * `$id` is null/malformed/unknown/under a different prefix.
     */
    private static function resolveName(?string $id): ?string
    {
        if ($id === null || ! str_contains($id, ':')) {
            return null;
        }

        $data = self::data();
        [$prefix, $name] = explode(':', $id, 2);

        if ($prefix !== $data['prefix']) {
            return null;
        }

        // Alias chains are one level deep in practice, but this stays
        // bounded in case a future catalog ever nests them.
        for ($hops = 0; $hops < 5 && $name !== null; $hops++) {
            if (isset($data['icons'][$name])) {
                return $name;
            }

            $name = $data['aliases'][$name]['parent'] ?? null;
        }

        return null;
    }

    private static function label(string $name): string
    {
        return ucwords(str_replace(['-', '_'], ' ', $name));
    }

    /**
     * @return array{prefix: string, width: int, height: int, icons: array<string, array{body: string, width?: int, height?: int}>, aliases: array<string, array{parent: string}>}
     */
    private static function data(): array
    {
        if (self::$data !== null) {
            return self::$data;
        }

        $path = resource_path('icons/devicon.json');

        if (! is_file($path)) {
            return self::$data = ['prefix' => 'devicon', 'width' => 24, 'height' => 24, 'icons' => [], 'aliases' => []];
        }

        $decoded = json_decode(file_get_contents($path), true);

        return self::$data = [
            'prefix' => $decoded['prefix'] ?? 'devicon',
            'width' => $decoded['width'] ?? 24,
            'height' => $decoded['height'] ?? 24,
            'icons' => $decoded['icons'] ?? [],
            'aliases' => $decoded['aliases'] ?? [],
        ];
    }
}
