name: 'traefik'
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    # Comandos para activar el modo DEBUG y el Dashboard
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

    ports:
      - "80:80"
      - "443:443"
      # Puerto para acceder al Dashboard
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Para que Traefik escuche a Docker
      - ./traefik.yml:/traefik.yml:ro # Archivo de configuración estática
      - ./acme.json:/acme.json # Para guardar los certificados SSL -> touch acme.json chmod 600 acme.json
    networks:
      - traefik-proxy
