log:
  level: INFO
api:
  dashboard: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: "m.test.notification@gmail.com"
      storage: "acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory" # Cambiar a staging para pruebas si es necesario
      httpChallenge:
        entryPoint: web
